### ISSUE TITLE
Watch for/foster/adopt `defer-hydration` attribute

### ISSUE THREAD

**Issue by zachleat** [11ty/is-land#14]
This will allow us to avoid the node renaming mechanism for lazy custom element hydration, which will be much faster.

via: https://github.com/11ty/is-land/issues/13#issuecomment-1312570393
Proposal: https://github.com/webcomponents-cg/community-protocols/pull/15

**Comment by zachleat** [comment]
Sample component implementation here: https://github.com/11ty/is-land/blob/fafe092b551d2f741203e9e86858b71df4f0c76d/lib/chocolate-web-component.js

**Comment by zachleat** [comment]
cc @dgp1130 this is shipping with is-land v3.0.0!

cross-linking to https://github.com/11ty/is-land/issues/13#issuecomment-1312570393

**Comment by dgp1130** [comment]
Awesome! Was planning to make a PR / file an issue about this after our discussion, but looks like you beat me to it. :grin:

**Comment by zachleat** [comment]
@dgp1130 Nerd sniped 😅
