### ISSUE TITLE
Add via cdn

### ISSUE THREAD

**Issue by TechAkayy** [11ty/is-land#22]
Can this library be used via cdn to progressively hydrate islands within a html file? 

When I install it via npm, I see it doesn't have any external dependencies. Thanks.

**Comment by jake-danton** [comment]
You can use ` <script type="module" src="https://esm.sh/@11ty/is-land@4.0.0"></script>` in your HTML (or https://unpkg.com/@11ty/is-land@4.0.0 or https://esm.run/@11ty/is-land@4.0.0 or any other CDN).

Example: https://codepen.io/JacobDanton/pen/oNRWwrr

**Comment by TechAkayy** [comment]
Thank you!
